### ISSUE TITLE
Missing J9dVGwSfo8Rwd4i9s7J41wk5Nv6xzrbFLQz9xzriC3wc (ORCA)

### ISSUE THREAD

**Issue by Kokkierobert** [moshthepitt/flm-jupiter-arb#4]
Keeps popping up when running, perhaps orca changed something?

Error: Missing J9dVGwSfo8Rwd4i9s7J41wk5Nv6xzrbFLQz9xzriC3wc
    at Gn.update (C:\Users\Administrator\Desktop\jupiter-arb\node_modules\@jup-ag\core\dist\core.cjs.development.min.js:1:132200)
    at J (C:\Users\ADesktop\jupiter-arb\node_modules\@jup-ag\core\dist\core.cjs.development.min.js:1:191760
    at async Ii.loadCoreData (C:\Users\Administrator\Desktop\jupiter-arb\node_modules\@jup-ag\core\dist\core.cjs.development.min.js:1:187742)
    at async Promise.all (index 0)
    at async Ii.load (C:\Users\Administrator\Desktop\jupiter-arb\node_modules\@jup-ag\core\dist\core.cjs.development.min.js:1:187057)

Node.js v18.15.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.dministrator\Desktop\jupiter-arb\node_modules\@jup-ag\core\dist\core.cjs.development.min.js:1:3424)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async C:\Users\Administrator\Desktop\jupiter-arb\node_modules\@jup-ag\core\dist\core.cjs.development.min.js:1:191760
    at async Ii.loadCoreData (C:\Users\Administrator\Desktop\jupiter-arb\node_modules\@jup-ag\core\dist\core.cjs.development.min.js:1:187742)
    at async Promise.all (index 0)
    at async Ii.load (C:\Users\Administrator\Desktop\jupiter-arb\node_modules\@jup-ag\core\dist\core.cjs.development.min.js:1:187057)

Node.js v18.15.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Kokkierobert** [comment]
Bot ran fine for weeks, checked on it and saw it closed, now never starting again, tried updating packages, reinstalling etc but nothing is helping. Any idea what it could be and how to resolve?
